title: COVID-19 and SARS-CoV2 info
author: me
email: jonathanmc@gmail.com
description: COVID-19 and SARS-CoV2 info

# social links
twitter_username: jmcrookston	# DO NOT include the @ character, or else the build will fail!
github_username:  jonathanmc	# DO NOT include the @ character, or else the build will fail!

show_excerpts: true 		# set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
#theme: minima
